### ISSUE TITLE
Make figures / text based around the cell type specificity of obvious facial markers visible from birth

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#21]
Jai had the figure showing that leaf nodes of HPO are more specific. Bobby to add an extra one showing the leaf nodes are more likely to only have one cell type association.

This principle can be followed through to the idea that facial morphological defects should be cell type specific.

E.g. there is a broad "abnormal lip morphology" which is associated with excitatory, inhibitory neurons, astrocytes and amacrine cells.

But a subphenotype of that, "short philtrum" is specific to excitatory neurons.

And a subphenotype "cleft upper lip" is astrocyte specific.

Can suggest then that obvious facial defects can be used to gain insight into the underlying cell types.

**Comment by bschilder** [comment]
Demonstrating the ontology level-celltype specificity relationship is done in Fig 2. Though it doesn't show a specific example, I think it's fine since it illustrates the broader point across all phenotypes.
https://github.com/neurogenomics/rare_disease_celltyping/blob/master/figures/manuscript_figures_july_2022.pdf
