### ISSUE TITLE
Find regulator genes

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rare_disease_celltyping#45]
@Al-Murphy `MultiEWCE::prioritise_targets` could be further extended by identifying key regulators of gene sets. This way, we can target all candidate genes by targeting a single regulator gene:

Useful tools:
- [`gprofiler2`](https://cran.r-project.org/web/packages/gprofiler2/vignettes/gprofiler2.html)
- [`enrichR`](https://cran.r-project.org/web/packages/enrichR/vignettes/enrichR.html)
- [`clusterProfiler`](https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html)

@Al-Murphy let me know if you have any other suggestions!

**Comment by Al-Murphy** [comment]
Only other one I thought of is [Reactome](https://bioconductor.org/packages/release/bioc/html/ReactomePA.html)

I don't know if identifying regulator genes is the ideal approach since there would always be off-target effects (by definition these are involved in the regulation of more than one gene). I think the ideal would be finding a gene in the same pathway as a gene of interest that we can't target (for example because of gene length) but that also meets all the other criteria you set out (i.e. specific to the cell type etc).
