### ISSUE TITLE
Include supplementary table with all the processed GeneCC values, exactly as used for the papers results

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#77]
![image](https://github.com/neurogenomics/rare_disease_celltyping/assets/33265555/116b5105-c30d-4529-96e9-2052b0d12389)

**Comment by bschilder** [comment]
Rather than splitting the data between supplementary materials and GitHub, I think it makes more sense to put them all in one place. GH Releases also has the advantage of being publicly available (not a guarantee with journals) and version controlled. Will therefore upload the data to GH Releases and include the link in the Data Availability section.

**Comment by bschilder** [comment]
Now included here in Releases. I've added descriptions of each file as well.
https://github.com/neurogenomics/MSTExplorer/releases/tag/v0.1.10
